TestRunner â€º exceptions in tests
\027[97mexceptions in tests \226\128\186 test framework handling of exceptions\027[39m
\r[3/3] Pending  \027[2m[0/3] Passed\027[22m  \027[2m[0/3] Failed\027[22m\r[2/3] Pending  \027[2m[0/3] Passed\027[22m  \027[31m[1/3] Failed\027[39m\r[1/3] Pending  \027[2m[0/3] Passed\027[22m  \027[31m[2/3] Failed\027[39m\r\027[2m[0/3] Pending\027[22m  \027[2m[0/3] Passed\027[22m  \027[31m[3/3] Failed\027[39m

\027[1m\027[31m  \226\128\162 exceptions in tests \226\128\186 test framework handling of exceptions \226\128\186 normal failure
\027[39m\027[22m    \027[2mexpect.string(\027[22m\027[31mreceived\027[39m\027[2m).toEqual(\027[22m\027[32mexpected\027[39m\027[2m)\027[22m
    
    Expected value to equal:
      \027[32m\"bar\"\027[39m
    Received:
      \027[31m\"foo\"\027[39m
    
    Difference:
      \027[31mfoo\027[39m\027[32mbar\027[39m

\027[1m\027[31m  \226\128\162 exceptions in tests \226\128\186 test framework handling of exceptions \226\128\186 uninlineable exception output\027[39m\027[22m
    Exception \027[2mInvalid_argument(\"I'm invalid :(\")\027[22m



\027[1m\027[31m  \226\128\162 exceptions in tests \226\128\186 test framework handling of exceptions \226\128\186 inline exception output\027[39m\027[22m
    Exception \027[2mNot_found\027[22m


